name: albamate
description: "알바메이트 - 똑똑한 알바 관리 앱"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4

  # 상태관리
  provider: ^6.1.2

  # 달력
  table_calendar: ^3.1.2

  # 날짜/시간 포맷
  intl: ^0.19.0

  # 로컬 저장소
  shared_preferences: ^2.3.2

  # URL 링크 열기
  url_launcher: ^6.3.0

  # 아이콘
  flutter_slidable: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true